version: '3.8'
name: blogtastic
services:
  blogtastic:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      blogtastic-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://blogtastic-db:5432/blog
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      #- SPRING_JPA_HIBERNATE_DDL_AUTO=update

  blogtastic-db:
    image: postgres:15.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=bloguser
      - POSTGRES_DB=blog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data: